# Generated by Django 4.1 on 2022-08-10 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balancete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('balancete_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.balancete')),
                ('titular_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('balancete_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.balancete')),
                ('titular_saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='balancete',
            name='titular_balancete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.usuario'),
        ),
    ]
