# Generated by Django 4.1 on 2022-08-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoFinancas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancete',
            name='entrada',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='balancete',
            name='saida',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
