# Generated by Django 4.1 on 2022-08-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoFinancas', '0002_alter_despesa_balancete_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='balancete_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoFinancas.balancete'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='balancete_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoFinancas.balancete'),
        ),
    ]
