# Generated by Django 4.1 on 2022-08-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoFinancas', '0002_alter_balancete_entrada_alter_balancete_saida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancete',
            old_name='titular',
            new_name='titular_balancete',
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='titular',
            new_name='titular_entrada',
        ),
        migrations.RenameField(
            model_name='saida',
            old_name='titular',
            new_name='titular_saida',
        ),
    ]
