# Generated by Django 4.0.4 on 2022-08-05 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoFinancas', '0002_receitas_alter_despesas_valor_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balancete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('Despesas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoFinancas.despesas')),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoFinancas.usuario')),
                ('receita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoFinancas.receitas')),
            ],
        ),
    ]
