# Generated by Django 4.0.4 on 2022-08-05 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoFinancas', '0003_balancete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancete',
            name='Usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.usuario'),
        ),
    ]
