# Generated by Django 4.1 on 2022-08-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoFinancas', '0003_rename_titular_balancete_titular_balancete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancete',
            old_name='entrada',
            new_name='saldo',
        ),
        migrations.RemoveField(
            model_name='balancete',
            name='saida',
        ),
    ]
