# Generated by Django 4.0.4 on 2022-08-05 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoFinancas', '0004_alter_balancete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancete',
            name='Usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.usuario'),
        ),
        migrations.RemoveField(
            model_name='balancete',
            name='receita',
        ),
        migrations.AddField(
            model_name='balancete',
            name='receita',
            field=models.ManyToManyField(null=True, to='ProjetoFinancas.receitas'),
        ),
    ]
