# Generated by Django 4.0.4 on 2022-08-05 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoFinancas', '0005_alter_balancete_usuario_remove_balancete_receita_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancete',
            old_name='Despesas',
            new_name='despesas',
        ),
        migrations.RemoveField(
            model_name='balancete',
            name='receita',
        ),
        migrations.AddField(
            model_name='balancete',
            name='receita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.receitas'),
        ),
    ]
