# Generated by Django 4.0.4 on 2022-08-05 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoFinancas', '0006_rename_despesas_balancete_despesas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancete',
            old_name='Usuario',
            new_name='titular',
        ),
        migrations.RemoveField(
            model_name='despesas',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='receitas',
            name='descricao',
        ),
        migrations.AddField(
            model_name='despesas',
            name='titular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.usuario'),
        ),
        migrations.AddField(
            model_name='receitas',
            name='titular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.usuario'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.usuario')),
            ],
        ),
    ]
