# Generated by Django 4.0.4 on 2022-08-05 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjetoFinancas', '0007_rename_usuario_balancete_titular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancete',
            name='despesas',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.despesas'),
        ),
        migrations.AlterField(
            model_name='balancete',
            name='receita',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.receitas'),
        ),
        migrations.AlterField(
            model_name='balancete',
            name='titular',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.usuario'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='titular',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.usuario'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='titular',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
