# Generated by Django 4.0.4 on 2022-08-05 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoFinancas', '0009_alter_balancete_despesas_alter_balancete_receita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancete',
            name='despesas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.despesas'),
        ),
        migrations.AlterField(
            model_name='balancete',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.receitas'),
        ),
        migrations.AlterField(
            model_name='balancete',
            name='titular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.usuario'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='titular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.usuario'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='titular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoFinancas.usuario'),
        ),
    ]
